# either set server.port as system property using command line option to jvm -Dserver.port=6583
# java -Dserver.port=6583 -jar target/activity-server-1.0.jar
# java -jar target/activity-server-1.0.jar --server.port=6583
server:
  port: 8081
  servlet:
    contextPath: /rain-server
  error:
    whitelabel:
      enabled: false

rain:
  home:
    province: yizheng
    member-number: 3
    member: bb, mm, yy
  company:
    province: nanjing
    member-number: 2
    member: qiangqiang, weiwei
